[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
# family = "HackNerdFont"
# style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[mouse]
hide_when_typing = true


